src/objects/AcccApplicationLog__c.object
<CustomObject>
    <description>The application log is used to store information around the underlying code. Also, provides a way to trace and monitor applications</description>
    <fields>
        <fullName>DebugLevel__c</fullName>
        <description>Error, Info, Warning, Debug</description>
        <inlineHelpText>Error, Info, Warning, Debug</inlineHelpText>
        <label>DebugLevel</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Debug</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Finest</fullName>
                </value>
                <value>
                    <fullName>Fine</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                    <default>true</default>
                    <label>Info</label>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Finer</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <label>Exception</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IntegrationPayload__c</fullName>
        <description>If log is integration related show payload</description>
        <inlineHelpText>If log is integration related show payload</inlineHelpText>
        <label>IntegrationPayload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>InvocationType__c</fullName>
        <description>invoc)ation type ( batch, future, etc</description>
        <label>InvocationType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message to log</description>
        <inlineHelpText>Message to log</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReferenceId__c</fullName>
        <description>The related record id</description>
        <inlineHelpText>The related record id</inlineHelpText>
        <label>ReferenceId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenceInfo__c</fullName>
        <description>The related record info (e.g. Apex Batch Job Id, Contact etc)</description>
        <inlineHelpText>The related record info (e.g. Apex Batch Job Id, Contact etc)</inlineHelpText>
        <label>ReferenceInfo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Source (i.e. class name)</description>
        <inlineHelpText>Source (i.e. class name)</inlineHelpText>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StackTrace__c</fullName>
        <description>Raw exception stack trace for unhandled errors</description>
        <inlineHelpText>Raw exception stack trace for unhandled errors</inlineHelpText>
        <label>StackTrace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>user name</description>
        <label>Username</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Accc Application Log</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>Accc Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accc Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/accc_BatchApexErrorEventHandler.cls
/**
 * Copyright (c) 2016-2019, Bill Anderson.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   * Neither the name of Bill Anderson nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Bill Anderson
 * @date 01/04/2019
 *
 * @description Handles BatchApexError. This simple mechanism just logs the data. It needs refactoring!
 *
 * Note, A. Fawcett ( see reference below) implemented a retry on the Batch
 *
 * @group Platform Events Handling
 */
public virtual class accc_BatchApexErrorEventHandler extends accc_EventBase {

	static final String DEBUG_LEVEL = 'Debug';
	static final String ERROR_LEVEL = 'Error';
	static final String INTEGRATION_PAYLOAD = 'Batch';
	
	@TestVisible
	static Boolean causeExceptionForTesting = false;
	
	/**
	 * @description Platform events only supports after insert
	 *
	 * @param List<SObject> list of new sobjects
	 */
	public virtual override void onAfterInsertChild(List<SObject> newItems) {
		this.records(newItems);
		// Query associated AsyncApexJobs (borrow portions from A. Fawcett [see below])
		// TODO: Use force-di to inject a test JobInfoResolver
		Map<Id, JobInfo> jobs = this.getJobInformationFromJobIds();
		try {

			// if testing are we throwing an exception
			if  (accc_ApexConstants.UnitTestsRunning) {
				if ( accc_BatchApexErrorEventHandler.causeExceptionForTesting ) {
					throw new accc_ApexApplicationException(DEBUG_LEVEL);
				}
			}
			List<AcccApplicationLog__c> entries = new List<AcccApplicationLog__c>();

			for ( BatchApexErrorEvent event : (List<BatchApexErrorEvent>)this.records()) {
				JobInfo asyncApexJob = jobs.get(event.AsyncApexJobId);
				// job present
				if (asyncApexJob != null) {

					entries.add(new AcccApplicationLog__c(
					                DebugLevel__c = ERROR_LEVEL,
					                Username__c = UserInfo.getUserName(),
					                Exception__c = event.ExceptionType,
					                ReferenceId__c = event.RequestId,
					                IntegrationPayload__c = INTEGRATION_PAYLOAD,
					                Source__c = asyncApexJob.ApexClassName,
					                ReferenceInfo__c = event.JobScope,
					                Message__c =   event.Message,
					                StackTrace__c = event.StackTrace,
					                InvocationType__c = asyncApexJob.toString()
					            ));
				}
			}// end for

			// anything to log
			if ( entries.size() > 0 ) {
				accc_ApplicationLog applLog = new accc_ApplicationLog();
				applLog.log(entries);
			}

		} catch (Exception excp) {
			// process exception, handle w/ care
			accc_ApexEnvironment.getRuntimeEnvironment().exceptionHandler().process(excp, true);
		}

	} // end of afterInsert

	/**
	 * @description get job information from the incoming event data
	 *
	 * @return Map of Job Info by job id
	 */
	private Map<Id, JobInfo> getJobInformationFromJobIds() {
		// Query associated AsyncApexJobs
		Set<Id> asyncApexJobIds = new Set<Id>();
		for (BatchApexErrorEvent evt :  (List<BatchApexErrorEvent>)this.records() ) {
			asyncApexJobIds.add(evt.AsyncApexJobId);
		}
		// TODO: Use force-di to inject a test JobInfoResolver
		return new RuntimeJobInfoResolver().resolveById(asyncApexJobIds);

	} // end of getJobInformationFromJobIds

	//====================================================================================
	//
	// The code below was borrowed from Andy's Github ...
	// Borrowed from https://raw.githubusercontent.com/afawcett/force-brf/master/force-brf/main/classes/brf_BatchApexErrorEvents.cls
	//
	//====================================================================================


	// Abstract queries made against AsyncApexJob to aid testability
	public abstract class JobInfoResolver {
		/**
		* @description Borrowed from https://raw.githubusercontent.com/afawcett/force-brf/master/force-brf/main/classes/brf_BatchApexErrorEvents.cls
		* Getting Job Information
		*
		* @param jobIds job ids of the batch jobs
		*
		*/
		public abstract Map<Id, JobInfo> resolveById(Set<Id> jobIds);
	}// end of JobInfoResolver
	/**
	 * @description run time job resolver
	 *
	 */
	public class RuntimeJobInfoResolver extends JobInfoResolver {
		/**
		* @description Borrowed from https://raw.githubusercontent.com/afawcett/force-brf/master/force-brf/main/classes/brf_BatchApexErrorEvents.cls
		* Getting Job Information
		*
		* @param jobIds job ids of the batch jobs
		*
		*/
		public override Map<Id, JobInfo> resolveById(Set<Id> jobIds) {
			Map<Id, JobInfo> jobsById = new Map<Id, JobInfo>();
			for (AsyncApexJob job : [select id, CreatedDate, ApexClass.Name from AsyncApexJob where Id IN :jobIds]) {
				JobInfo jobInfo = new JobInfo();
				jobInfo.id = job.Id;
				jobInfo.apexClassName = job.ApexClass.Name;
				jobInfo.createdDate = job.CreatedDate;
				jobsById.put(jobInfo.id, jobInfo);
			}

			return jobsById;
		}
	}
	/**
	 * @description plain old apex class (POAC) -- container only
	 *
	 */
	public class JobInfo {
		public Id id;
		public String apexClassName;
		public DateTime createdDate;
		public override String toString() {
			return 'Job Id:' + this.id 
				+ ', Classname:' + this.apexClassName 
				+ ', CreatedDate:' + this.createdDate;
		}
	} // end of JobInfo

} // end of accc_BatchApexErrorEventHandler