src/objects/accc_Log__e.object
<CustomObject>
    <description>accc Log information</description>
    <fields>
        <fullName>DebugLevel__c</fullName>
        <description>Debug level (debug, error, warning, info)</description>
        <label>DebugLevel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogCode__c</fullName>
        <description>Log Code -- application specific</description>
        <label>LogCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message</description>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Source</description>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>User name</description>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>accc_Log</label>
    <pluralLabel>accc_Logs</pluralLabel>
</CustomObject>

src/objects/ApplicationLog__c.object
<CustomObject>
    <description>The application log is used to store information around the underlying code. Also, provides a way to trace and monitor applications</description>
    <fields>
        <fullName>DebugLevel__c</fullName>
        <description>Error, Info, Warning, Debug</description>
        <inlineHelpText>Error, Info, Warning, Debug</inlineHelpText>
        <label>DebugLevel</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Debug</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Fiest</fullName>
                </value>
                <value>
                    <fullName>Fine</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                    <default>true</default>
                    <label>Info</label>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <label>Exception</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IntegrationPayload__c</fullName>
        <description>If log is integration related show payload</description>
        <inlineHelpText>If log is integration related show payload</inlineHelpText>
        <label>IntegrationPayload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>InvocationType__c</fullName>
        <description>invoc)ation type ( batch, future, etc</description>
        <label>InvocationType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogCode__c</fullName>
        <description>Either the exception error code of custom org code for record</description>
        <inlineHelpText>Either the exception error code of custom org code for record</inlineHelpText>
        <label>LogCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message to log</description>
        <inlineHelpText>Message to log</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReferenceId__c</fullName>
        <description>The related record id</description>
        <inlineHelpText>The related record id</inlineHelpText>
        <label>ReferenceId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenceInfo__c</fullName>
        <description>The related record info (e.g. Apex Batch Job Id, Contact etc)</description>
        <inlineHelpText>The related record info (e.g. Apex Batch Job Id, Contact etc)</inlineHelpText>
        <label>ReferenceInfo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceFunction__c</fullName>
        <label>SourceFunction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Source (i.e. class name)</description>
        <inlineHelpText>Source (i.e. class name)</inlineHelpText>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StackTrace__c</fullName>
        <description>Raw exception stack trace for unhandled errors</description>
        <inlineHelpText>Raw exception stack trace for unhandled errors</inlineHelpText>
        <label>StackTrace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Statistics__c</fullName>
        <label>Statistics</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UserRoleId__c</fullName>
        <label>UserRoleId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>user name</description>
        <label>Username</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>profileId__c</fullName>
        <description>profile id</description>
        <label>profileId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ApplicationLog</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>ApplicationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ApplicationLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/accc_MessageTransformation.cls
/**
 * Copyright (c) 2016-2018, Bill Anderson.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   * Neither the name of Bill Anderson nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 * @author Bill Anderson
 * @description  Translate messages from one type to another
 * @group Common Layer
 */
public without sharing class accc_MessageTransformation {

    /**
     * @description translate a ApplicationLog to a accc_Log__e
     *
     * @param appLog Application Log
     * @return accc_Log__e
     */
    public static accc_Log__e translate(ApplicationLog__c datum) {
        accc_Log__e result = null;

        if ( datum != null ) {
            result = new accc_Log__e(LogCode__c = string.valueOf(datum.LogCode__c),
                                Message__c = accc_MessageTransformation.mergeApplicationLogData(datum),
                                Username__c = UserInfo.getUserId());
        }
        return result;

    } // end of translate
    /**
     * @description translate a log record into an ApplicationLog__c
     *
     * @param LoggingLevel logging level
     * @param Object the message
     * @return ApplicationLog__c
     */
    public static ApplicationLog__c translate(LoggingLevel level, Object message) {
        ApplicationLog__c result = null;

        if ( message != null ) {
            result = new ApplicationLog__c(LogCode__c = string.valueOf(level),
                                           DebugLevel__c = level.name(),
                                           Message__c =  string.valueOf(message),
                                           Source__c = 'ApplicationLog__c',
                                           OwnerId = UserInfo.getUserId(),
                                           Username__c = UserInfo.getUserId());
        }
        return result;
    } // end of translate

    /**
     * @description translate a log record into an ApplicationLog__c
     *
     * @param LoggingLevel logging level
     * @param List<Object> the messages
     * @return List<ApplicationLog__c>
     */
    public static List<ApplicationLog__c> translate(LoggingLevel level, List<Object> messages) {
        List<ApplicationLog__c> result = null;
        ApplicationLog__c item = null;

        if ( messages != null && messages.size() > 0) {
            result = new List<ApplicationLog__c> ();
            for ( integer inx = 0; inx < messages.size(); inx++) {
                item = accc_MessageTransformation.translate(level, messages[inx]);
                if ( item != null ) {
                    result.add(item);
                }
            }
        }
        return result;
    } // end of translate

    /**
     * @description translate a ApplicationLog to a accc_Log__e
     *
     * @param appLog Application Log
     * @return accc_Log__e
     */
    public static List<accc_Log__e> translate(List<ApplicationLog__c> listDatum) {
        List<accc_Log__e> result = null;

        if ( listDatum != null && listDatum.size() > 0) {
            accc_Log__e elog;
            result = new List<accc_Log__e>();
            for (ApplicationLog__c datum : listDatum) {
                elog = accc_MessageTransformation.translate(datum);
                if ( elog != null) {
                    result.add(elog);
                }
            }
        }
        return result;

    } // end of translate

    /**
     * @description translate a accc_Log__e to a ApplicationLog__c
     *
     * @param eLog accc_Log__e
     * @return ApplicationLog__c
     */
    public static ApplicationLog__c translate(accc_Log__e datum) {
        ApplicationLog__c result = null;

        if ( datum != null ) {
            result = new ApplicationLog__c(LogCode__c = string.valueOf(datum.LogCode__c),
                                           Message__c =  string.valueOf(datum.Message__c),
                                           Source__c = 'Log Platform Event',
                                           OwnerId = UserInfo.getUserId(),
                                           Username__c = UserInfo.getUserId());
        }
        return result;

    } // end of translate
    /**
     * @description translate a accc_Log__e to a ApplicationLog__c
     *
     * @param List<accc_Log__e> list of log events
     * @return List<ApplicationLog__c> list of applicationLog
     */
    public static List<ApplicationLog__c> translate(List<accc_Log__e> listDatum) {
        List<ApplicationLog__c> result = null;

        if ( listDatum != null && listDatum.size() > 0 ) {
            ApplicationLog__c appLog;
            result = new List<ApplicationLog__c>();
            for (accc_Log__e datum : listDatum ) {
                appLog = accc_MessageTransformation.translate(datum);
                if ( appLog != null) {
                    result.add(appLog);
                }
            }
        }
        return result;

    } // end of translate
    /**
     * @description  merge all fields into a single string for consumption
     *
     * @param ApplicationLog__c the application log
     * @return string, merge data of ApplicationLog
     */
    public static string mergeApplicationLogData(ApplicationLog__c datum) {
        String result = '';
        String placeholder = 'User Role Id: {0}\n,Debug Level: {1},\nMessage: {2},\nException: {3},\nIntegration Payload: {4},\nProfile Id: {5},\nReference Id: {6},\nReference Info: {7},\nSource: {8},\nSource Function: {9},\nStack Trace: {10}\nStatistics: {11}\n';

        if ( datum != null ) {
            List<String> fillers = new List<String> {
                datum.UserRoleId__c
                , datum.DebugLevel__c
                , datum.Message__c
                , datum.Exception__c
                , datum.IntegrationPayload__c
                , datum.InvocationType__c
                , datum.profileId__c
                , datum.ReferenceId__c
                , datum.ReferenceInfo__c
                , datum.Source__c
                , datum.SourceFunction__c
                , datum.StackTrace__c
                , datum.Statistics__c
            };

            result = String.format(placeholder, fillers);
        }
        return result;

    } // end of mergeApplicationLogData

} // end of accc_MessageTransformation