src/objects/accc_Apex_Code_Configuration__mdt.object
<CustomObject>
    <description>Apex Configuration is used by the underlying cross-cutting framework to determine how to behave. The behavior can change based on concreteness of the classes. The interfaces are the contract to inter-operate</description>
    <fields>
        <fullName>CacheResource__c</fullName>
        <defaultValue>&apos;ApexCache&apos;</defaultValue>
        <description>class that implements class ICache</description>
        <inlineHelpText>class that implements class ICache</inlineHelpText>
        <label>Cache Resource</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CacheStrategyInvocation__c</fullName>
        <description>Class use to determine the cache strategy</description>
        <inlineHelpText>Class use to determine the cache strategy</inlineHelpText>
        <label>Cache Strategy Invocation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CacheStrategy__c</fullName>
        <description>Cache Strategy class</description>
        <inlineHelpText>Cache Strategy class</inlineHelpText>
        <label>Cache Strategy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConfigurationResource__c</fullName>
        <defaultValue>&apos;accc_VirtualCustomSettings&apos;</defaultValue>
        <description>Configuration Resource , such custom settings, static resources etc.</description>
        <inlineHelpText>Configuration Resource , such custom settings, static resources etc.</inlineHelpText>
        <label>Configuration Resource</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionFormatter__c</fullName>
        <defaultValue>&apos;ExceptionFormatter&apos;</defaultValue>
        <description>Formats exceptions</description>
        <inlineHelpText>Formats exceptions</inlineHelpText>
        <label>Exception Formatter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionHandler__c</fullName>
        <description>class that implements IApexExceptionHandler</description>
        <inlineHelpText>class that implements IApexExceptionHandler</inlineHelpText>
        <label>Exception Handler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionPolicyHandler__c</fullName>
        <defaultValue>&apos;ApexExceptionPolicyStrategy&apos;</defaultValue>
        <description>How to handle exceptions</description>
        <inlineHelpText>How to handle exceptions</inlineHelpText>
        <label>Exception Policy Handler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FactoryResource__c</fullName>
        <defaultValue>&apos;ApexObjectFactory&apos;</defaultValue>
        <description>The factory used to create all the classes ( those that have an interface)</description>
        <inlineHelpText>The factory used to create all the classes ( those that have an interface)</inlineHelpText>
        <label>Factory Resource</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FallbackResource__c</fullName>
        <description>class that implements IFallbackResources</description>
        <label>Fallback Resources</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogFormatter__c</fullName>
        <defaultValue>&apos;accc_ApexLogFormatter&apos;</defaultValue>
        <description>The default formatter for log data</description>
        <inlineHelpText>The default formatter for log data ( see accc_ApexLogFormatter)</inlineHelpText>
        <label>Log Formatter</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logger__c</fullName>
        <defaultValue>&apos;ApexLogger&apos;</defaultValue>
        <description>The logging class that implements ILogger</description>
        <inlineHelpText>The logging class that implements ILogger</inlineHelpText>
        <label>Logger</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreviousTransactionResultResource__c</fullName>
        <defaultValue>&apos;ApexPreviousTransactionResult&apos;</defaultValue>
        <description>How to handle a previous transaction result class</description>
        <inlineHelpText>How to handle a previous transaction result class</inlineHelpText>
        <label>Previous Transaction Result Resource</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RuntimeEnvironment__c</fullName>
        <defaultValue>&apos;ApexBaseRuntimeEnvironment&apos;</defaultValue>
        <description>the class runtime environment</description>
        <inlineHelpText>the class runtime environment</inlineHelpText>
        <label>Runtime Environment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendEmailChannel__c</fullName>
        <defaultValue>&apos;ApexMailMessageSender&apos;</defaultValue>
        <description>How to send email class</description>
        <inlineHelpText>How to send email class</inlineHelpText>
        <label>Send Email Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Accc Apex Code Configuration</label>
    <pluralLabel>Accc Apex Code Configurations</pluralLabel>
</CustomObject>

src/classes/accc_CrossCuttingConfigDataModel.cls
/**
 * Copyright (c) 2016-2019, Bill Anderson.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   * Neither the name of Bill Anderson nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 * @author Bill Anderson
 * @description  External representation of the data cached metadata. Providing a
 * wrapper around the internal data mapper allows one to vary the metadata w/o having to
 * change ALL dependencies. [Added layer of indirection to adjust for change].
 *
 * To Add a new resource: See Steps below
 *
 * @group Common Layer
 */
public without sharing class accc_CrossCuttingConfigDataModel extends accc_BaseMdtDataModel {

    /////////////////////////////////////////////////////////////////////////////////////////
    //
    // Data Members
    //
    /////////////////////////////////////////////////////////////////////////////////////////

    // our field we categorize on ( this will hold the environment [test, debug,prod])
    @TestVisible
    static final String CATEGORY_FIELD = 'DeveloperName';

    // the custom mdt name
    @TestVisible
    static private final string MDT_Name = 'accc_Apex_Code_Configuration__mdt';
    // fields supported on this custom mdt
    // Step 1a. Added field name here, ie. 'LogFormatter__c'
    @TestVisible
    static private final List<String> FieldList = new List<String> {
        'CacheResource__c'
        , 'ConfigurationResource__c'
        , 'CacheStrategyInvocation__c'
        , 'CacheStrategy__c'
        , 'ExceptionHandler__c'
        , 'ExceptionFormatter__c'
        , 'ExceptionPolicyHandler__c'
        , 'FallbackResource__c'
        , 'FactoryResource__c'
        , 'Logger__c'
        , 'LogFormatter__c'
        , 'PreviousTransactionResultResource__c'
        , 'RuntimeEnvironment__c'
        , 'SendEmailChannel__c'

    };
    /////////////////////////////////////////////////////////////////////////////////////////
    //
    // Ctors
    //
    /////////////////////////////////////////////////////////////////////////////////////////
    /**
     * @description data cache information - view representation , allows for changes
     * in the implementation (data representation) w/o affecting the consumption [DAO]
     *
     * To Added New Resouce classes (Step 1b: Add data member here (i.e.,'logFormatterClass'))
     *
     */
    public class CrossCuttingConfigInformation extends accc_BaseMdtDataModel.BaseDataModelInformation {

        public string cacheClass;
        public String exceptionHandlerClass;
        public String fallbackResourcesClass;
        public String loggingClass;
        public String logFormatterClass;
        public String cacheStrategyClass;
        public String cacheStrategyInvocationClass;
        public String configurationClass;
        public String exceptionFormatterClass;
        public String exceptionPolicyHandlerClass;
        public String previousTransactionResultResourceClass;
        public String sendEmailChannelClass;
        public String runtimeEnvironmentClass;
        public String factoryClass;

    } // end of CrossCuttingConfigInformation

    /**
     * @description default ctor
     *
     */
    public accc_CrossCuttingConfigDataModel() {
        super(MDT_Name, CATEGORY_FIELD);

    } // end of ctor
    /////////////////////////////////////////////////////////////////////////////////////////
    //
    // Protected Methods
    //
    /////////////////////////////////////////////////////////////////////////////////////////
    /**
     * @description populate our external view of the data cache structure
     *
     * @param cacheMDT the data cache Metadata
     * @param the map of data
     * @return our view of the data ( allows us to change internally)
     */
    @TestVisible
    protected override List<accc_BaseMdtDataModel.BaseDataModelInformation> populateFromDataObjectChild(List<SObject> data) {
        List<CrossCuttingConfigInformation> results = new List<CrossCuttingConfigInformation> ();
        List<accc_Apex_Code_Configuration__mdt> cmdts = (List<accc_Apex_Code_Configuration__mdt>) data;


        if (cmdts != null && cmdts.size() > 0) {
            for (accc_Apex_Code_Configuration__mdt cmdt : cmdts) {
                CrossCuttingConfigInformation result = new CrossCuttingConfigInformation();
                this.setValues((accc_BaseMdtDataModel.BaseDataModelInformation)result, cmdt.Label, cmdt.NamespacePrefix, cmdt.DeveloperName);

                /* To Added New Resouce classes (Step 2: Assign data member here (i.e.,'logFormatterClass')
                 *                                       from SF Object 'LogFormatter__c')
                 *
                 *                               Step 3: Ensure you add field to 'accc_Apex_Code_Configuration__mdt'
                 *                               Step 4: Ensure Fallback Resources have the Resource Name (see accc_ApexConstants and accc_ApexKnownCCConcernsFallback)
                 **/

                result.cacheClass = accc_Apexutilities.normalizeString(cmdt.CacheResource__c, true);
                result.cacheStrategyInvocationClass = accc_Apexutilities.normalizeString(cmdt.CacheStrategyInvocation__c, true);
                result.cacheStrategyClass = accc_Apexutilities.normalizeString(cmdt.CacheStrategy__c, true);
                result.configurationClass = accc_Apexutilities.normalizeString(cmdt.ConfigurationResource__c, true);
                result.exceptionFormatterClass = accc_Apexutilities.normalizeString(cmdt.ExceptionFormatter__c, true);
                result.exceptionPolicyHandlerClass = accc_Apexutilities.normalizeString(cmdt.ExceptionPolicyHandler__c, true);
                result.exceptionHandlerClass = accc_Apexutilities.normalizeString(cmdt.ExceptionHandler__c, true);
                result.factoryClass = accc_Apexutilities.normalizeString(cmdt.FactoryResource__c, true);
                result.fallbackResourcesClass = accc_Apexutilities.normalizeString(cmdt.FallbackResource__c, true);
                result.loggingClass = accc_Apexutilities.normalizeString(cmdt.Logger__c, true);
                result.logFormatterClass = accc_Apexutilities.normalizeString(cmdt.LogFormatter__c, true);
                result.previousTransactionResultResourceClass = accc_Apexutilities.normalizeString(cmdt.PreviousTransactionResultResource__c, true);
                result.sendEmailChannelClass = accc_Apexutilities.normalizeString(cmdt.SendEmailChannel__c, true);
                result.runtimeEnvironmentClass = accc_Apexutilities.normalizeString(cmdt.RuntimeEnvironment__c, true);

                results.add(result);
            }
        } // endif

        return results;
    } // end of populateFromDataObjectChild
    /**
     * @description allow the child to return their custom fields to select
     * @return collection of field name
     */
    @TestVisible
    protected override List<String> getSelectFields() {
        return accc_CrossCuttingConfigDataModel.FieldList;
    } // end of getSelectFields
    /**
     * @description used to get MDT data and remap to our external view for testing
     *
     * @return CacheInformation our view
     */
    @TestVisible
    protected override accc_BaseMdtDataModel.BaseDataModelInformation getTestInformationByLookup() {
        List<accc_BaseMdtDataModel.BaseDataModelInformation> results = super.getInformationByLookup(accc_ApexConstants.TEST_CATEGORY, accc_ControlPolicySearchEnum.byLabel);

        return results != null && results.size() > 0 ? results[0] : null;
    } // end of getTestInformationByLookup


} // end of accc_CrossCuttingConfigDataModel