src/objects/accc_Log__e.object
<CustomObject>
    <description>accc Log information</description>
    <fields>
        <fullName>DebugLevel__c</fullName>
        <description>Debug level (debug, error, warning, info)</description>
        <label>DebugLevel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message</description>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>accc_Log</label>
    <pluralLabel>accc_Logs</pluralLabel>
</CustomObject>

src/objects/ACCC_Log_Event__e.object
<CustomObject>
    <description>Log Events generally capture information regarding SObjectcs. It provides a way to have audits of transactions (CDC) so that one may have history of the flow of information. Note, the &apos;Publish Behavior&apos; is &apos;Immediately&apos;. This is to ensure ANY action is NOT based on the atomic attribute of the transaction scope.</description>
    <fields>
        <fullName>Action__c</fullName>
        <description>Action should correlate to : Create, Update,Delete, Undelete (if an object operation)</description>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateTime__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Date time of the event</description>
        <label>DateTime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <description>If any exception is known</description>
        <label>Exception</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <defaultValue>&apos;&apos;</defaultValue>
        <description>An external Id of the main object, if known;otherwise, null or empty</description>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <description>The JSON payload</description>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Number__c</fullName>
        <label>Total Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TransactionId__c</fullName>
        <description>Transaction Id</description>
        <label>TransactionId</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <description>User id of the originator (not the created by)</description>
        <label>UserId</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <defaultValue>&apos;1.0.0.0&apos;</defaultValue>
        <description>Version of the message event</description>
        <label>Version</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ACCC Log Event</label>
    <pluralLabel>ACCC Log Events</pluralLabel>
</CustomObject>

src/objects/AcccApplicationLog__c.object
<CustomObject>
    <description>The application log is used to store information around the underlying code. Also, provides a way to trace and monitor applications</description>
    <fields>
        <fullName>DebugLevel__c</fullName>
        <description>Error, Info, Warning, Debug</description>
        <inlineHelpText>Error, Info, Warning, Debug</inlineHelpText>
        <label>DebugLevel</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Debug</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Finest</fullName>
                </value>
                <value>
                    <fullName>Fine</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                    <default>true</default>
                    <label>Info</label>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Finer</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <label>Exception</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message to log</description>
        <inlineHelpText>Message to log</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Accc Application Log</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>Accc Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accc Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/accc_MessageTransformationTest.cls
/**
 * Copyright (c) 2016-2019, Bill Anderson.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   * Neither the name of Bill Anderson nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 * @author Bill Anderson
 * @description  Test message transformation
 * @group Common Test Layer
 */
@isTest
private class accc_MessageTransformationTest {

	@isTest
	static void testtranslateToLogE() {
		String msg = 'testtranslateToLogE';
		AcccApplicationLog__c apl = new AcccApplicationLog__c(Message__c = msg);
		accc_Log__e loge = accc_MessageTransformation.translate(apl);
		system.assertEquals(true, loge.Message__c.contains(msg));
	} // end of testtranslateToLogE

	@isTest
	static void testtranslateFromObjectToApplicationLog() {
		String msg = 'testtranslateToApplicationLog';
		accc_Log__e loge = new accc_Log__e(Message__c = msg);
		AcccApplicationLog__c apl = accc_MessageTransformation.translate(loge);
		
		system.assertEquals(true, apl.Message__c.contains(msg));
	} // end of testtranslateFromObjectToApplicationLog

	@isTest
	static void testtranslateToApplicationLog() {
		String msg = 'testtranslateToApplicationLog';
		Object loge = msg;
		AcccApplicationLog__c apl = accc_MessageTransformation.translate(LoggingLevel.DEBUG, loge);
		system.assertEquals(true, apl.DebugLevel__c == LoggingLevel.DEBUG.name());
		system.assertEquals(true, apl.Message__c.contains(msg));
	} // end of testtranslateToApplicationLog

	@isTest
	static void testtranslateToListLogE() {
		String msg = 'testtranslateToListLogE';
		List<AcccApplicationLog__c> apl = new List<AcccApplicationLog__c> { new AcccApplicationLog__c(Message__c = msg)};
		List<accc_Log__e> loge = accc_MessageTransformation.translate(apl);
		system.assertEquals(true, loge[0].Message__c.contains(msg));
	} // end of testtranslateToListLogE

	@isTest
	static void testtranslateListObjectToApplList() {
		String msg = 'testtranslateToListLogE';
		integer inx = 0;
		List<Object> apl = new List<Object> { '1', '2', '3'};
		List<AcccApplicationLog__c> alog = accc_MessageTransformation.translate(LoggingLevel.INFO, apl);
		for ( Object aMsg : apl) {
			system.assertEquals(true, alog[inx].Message__c.contains((String)aMsg));
			inx++;
		}
	} // end of testtranslateListObjectToApplList

	@isTest
	static void testtranslateToListApplicationLog() {
		String msg = 'testtranslateToListApplicationLog';
		List<accc_Log__e> loge = new List<accc_Log__e> {new accc_Log__e(Message__c = msg)};
		List<AcccApplicationLog__c> apl = accc_MessageTransformation.translate(loge);
		system.assertEquals(true, apl[0].Message__c.contains(msg));
	} // end of testtranslateToListApplicationLog

	@isTest
	static void testtranslateToListApplicationLogWithNull() {

		List<accc_Log__e> loge = null;
		List<AcccApplicationLog__c> apl = accc_MessageTransformation.translate(loge);
		system.assertEquals(true, apl == null);
	} // end of testtranslateToListApplicationLogWithNull

	@isTest
	static void testtranslateToListLogEWithNull() {

		List<AcccApplicationLog__c> apl = null;
		List<accc_Log__e> loge = accc_MessageTransformation.translate(apl);
		system.assertEquals(true, loge == null);
	} // end of testtranslateToListLogEWithNull

	@isTest
	static void testtranslateLogEntry() {

		List<ACCC_Log_Event__e> apl = generateLogEvent(10);
		List<AcccApplicationLog__c> loge = accc_MessageTransformation.translate(apl);
		system.assertEquals(true, loge.size() == apl.size());
	} // end of testtranslateLogEntry

	static List<ACCC_Log_Event__e> generateLogEvent(integer count){
		List<ACCC_Log_Event__e> entries = new List<ACCC_Log_Event__e>();
		ACCC_Log_Event__e datum;
		Integer ctSize = accc_CDCEventBase.CDC_KNOWN_CHANGE_TYPES.size()-1, 
		index=0;
		Id userId = UserInfo.getUserId();
		String uname = UserInfo.getName();
		Account acct= new Account();
 
		for ( integer inx=0; inx < count; inx++){
			entries.add( new ACCC_Log_Event__e(	Action__c= accc_CDCEventBase.CDC_KNOWN_CHANGE_TYPES[index++],
                                      	External_Id__c=accc_ApexUtilities.newGuid(),
                                      	TransactionId__c = accc_ApexUtilities.newGuid(),
                                      	Exception__c = (index == 3) ? 'accc_ApexApplicationException {}' : '',
                                      	Payload__c = JSON.serialize(acct),
                                    	UserId__c = userId,
									 	Version__c = '1.0.0.0',
										Sequence_Number__c = 1,
										Total_Number__c=1,
										DateTime__c = DateTime.now()
									)
						);
			index = index > ctSize ? 0 : index;
		}
		return entries;
	}
} // end of accc_MessageTransformationTest